### ISSUE TITLE
Inquiry about Data preprocessing

### ISSUE THREAD

**Issue by shwan333** [zxiang30/DLFS-Rec#1]
Hello, @zxiang30
I'm reading your paper and code, the paper looks valuable in the field of SR, thanks for the great work :)

I want to run your model on other datasets (e.g. amazon dataset, yelp) for research, what code could I use to preprocess it into the appropriate format? I searched all the code, but I could not find the preprocessing code.

Any help would be appreciated!

Regards,
Choi

**Comment by zxiang30** [comment]
@shwan97, thanks for your kind words. 

The dataset preprocessing code has been uploaded to the 'data' folder just now. It should be noted that the data preprocessing is specifically for the Amazon Reviews dataset, and does not include the Yelp dataset or any other datasets. In our paper, to maintain consistency in side information and facilitate experiments, we exclusively consider datasets from Amazon.

When preprocessing other datasets, you may adopt a similar approach as applied to the Amazon dataset, but be attentive to the selection of appropriate side information.

If you find it helpful, consider giving a star to our work.

**Comment by shwan333** [comment]
Thank you for providing the pre-processing code. It works. I gave a star for this good repository.
